[package]
name = "radio_comms"
version = "0.1.0"
authors = ["Neelay Junnarkar <neelay.junnarkar@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0.1"
rand = "0.6.1"
itertools = "0.8.0"
portaudio = "0.7.0"
lazy_static = "1.3.0"